
package Grafica;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;



/**
 *
 * @author Carlollos
 */
public class Index extends javax.swing.JFrame {

    public Perrera Lista;
   
    
    JPanel topPanel;
    JPanel PanelContenedor;
    JScrollPane sPane;
    int scrollBarSize = 0;
    boolean isVScrollVisible = false;
       
       
    public Index() {
        initComponents();
        Lista = new Perrera();
        
        topPanel = new JPanel();
        PanelContenedor = new JPanel();
        PanelContenedor.setLayout(new BoxLayout(PanelContenedor, BoxLayout.Y_AXIS));
         
        sPane = new JScrollPane(PanelContenedor, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        sPane.setPreferredSize(new Dimension(200, 300));
        sPane.getViewport().addChangeListener(new MyChangeListener());
        
        //scrollBarSize = ((Integer)UIManager.get("ScrollBar.width")) + 1;
         
                  
        this.PanelPrincipal.add(topPanel,BorderLayout.PAGE_START);
        this.PanelPrincipal.add(sPane, BorderLayout.CENTER);
        
        this.setLocationRelativeTo(null);//Centra el elemento en la pantalla
    }

      public class MyChangeListener implements ChangeListener {
        @Override
        public void stateChanged(ChangeEvent e) {
            isVScrollVisible = (sPane.getVerticalScrollBar().isVisible());
        }
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PanelMenu = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAgregar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbPrimerelemento = new javax.swing.JLabel();
        lbUlimoElemento = new javax.swing.JLabel();
        lbElementoActual = new javax.swing.JLabel();
        lbTamaño = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnEliminarPrimero = new javax.swing.JButton();
        btnEliminarUltimo = new javax.swing.JButton();
        txtEliminarIndice = new javax.swing.JTextField();
        btnEliminarIndice = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PanelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMenu.setBackground(new java.awt.Color(204, 204, 255));
        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        PanelMenu.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ingrese el nuevo dato y precione agregar");
        PanelMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Control de la lista");
        PanelMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        txtAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PanelMenu.add(txtAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 290, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tamaño Lista:");
        PanelMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 100, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Primer elemento:");
        PanelMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Ultimo elemento:");
        PanelMenu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Elemento Actual");
        PanelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        lbPrimerelemento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPrimerelemento.setForeground(new java.awt.Color(255, 51, 51));
        PanelMenu.add(lbPrimerelemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 80, 20));

        lbUlimoElemento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbUlimoElemento.setForeground(new java.awt.Color(255, 51, 51));
        PanelMenu.add(lbUlimoElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 80, 20));

        lbElementoActual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbElementoActual.setForeground(new java.awt.Color(255, 51, 51));
        PanelMenu.add(lbElementoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 80, 20));

        lbTamaño.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTamaño.setForeground(new java.awt.Color(255, 51, 51));
        PanelMenu.add(lbTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 60, 20));

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Eliminacion de datos");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        btnEliminarPrimero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminarPrimero.setText("Eliminar Primero");
        btnEliminarPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPrimeroActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarPrimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        btnEliminarUltimo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminarUltimo.setText("Eliminar Ultimo");
        btnEliminarUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUltimoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, 30));
        jPanel1.add(txtEliminarIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, 30));

        btnEliminarIndice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminarIndice.setText("Eliminar por indice");
        btnEliminarIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarIndiceActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Eliminar actual");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        PanelMenu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 440, 110));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Avanzar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Reiniciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        PanelMenu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 290, 80));

        getContentPane().add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 500, 540));

        PanelPrincipal.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
   
        if(txtAgregar.getText().equals("")){
            JOptionPane.showMessageDialog(null, "NO SE PERMITEN VALORES VACIOS");
        }else{
            Lista.AgregarPerro(txtAgregar.getText());
            Graficar();
            txtAgregar.setText("");
            Estadisticas();
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPrimeroActionPerformed
        
        if(Lista.TamañoLista!=0){
             Lista.EliminarPrimerPerro();
            Graficar();
            Estadisticas();
        }else{
                JOptionPane.showMessageDialog(null, "La cola esta vacia");
        }
       
        
    }//GEN-LAST:event_btnEliminarPrimeroActionPerformed

    private void btnEliminarUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUltimoActionPerformed
        if(Lista.TamañoLista!=0){
             Lista.EliminarUltimoPerro();
             Graficar();
             Estadisticas();
        }else{
                JOptionPane.showMessageDialog(null, "La cola esta vacia");
        }
       
        
    }//GEN-LAST:event_btnEliminarUltimoActionPerformed

    private void btnEliminarIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarIndiceActionPerformed
    
        
       if(Lista.TamañoLista!=0){
        
        int Indice = Integer.parseInt(txtEliminarIndice.getText());
        
        if(Indice>Lista.TamañoLista){
            JOptionPane.showMessageDialog(null, "Ingrese"
        + " un valor menor al tamaño de la lista TAMAÑO LISTA: "+Lista.TamañoLista);
        }
        else{
            Lista.EliminarPerroPorIndice(Indice);
            Graficar();
            Estadisticas();
        }
        
        
       }else{
               JOptionPane.showMessageDialog(null, "La cola esta vacia");
       }
        
    }//GEN-LAST:event_btnEliminarIndiceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
            Lista.Avanzar();
            Graficar();
            Estadisticas();
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
            Lista.Regresar();
            Graficar();
            Estadisticas();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        
        Lista.EliminarActual();
         Graficar();
         Estadisticas();
        
    }//GEN-LAST:event_jButton3ActionPerformed

     public void Limpiar(){
         PanelContenedor.removeAll();
         Revalidar();
    }//Fin Limpiar
     
    public void Revalidar(){
        PanelContenedor.revalidate();
        PanelContenedor.repaint();

        sPane.revalidate();
        sPane.repaint();
     }//Fin Revalidar
    
    public void Graficar(){
        //Limpiar panel primero
        Limpiar();
        
        if(Lista.ListaVacia()){
            
        }else{
        ArrayList<Canino> Elementos = Lista.ObtenerElementosGRAFICACION();
        
       if(Elementos == null){
           
       }else{
//        for (Canino Elemento : Elementos) {
//            System.out.println(Elemento.dato);
//        }
        
        int ContadorNulos = 1;
        for (Canino Elemento : Elementos) {
           
            JPanel PanelEtiqueta = new JPanel();
            PanelEtiqueta.setSize(new Dimension(100,50));
            PanelEtiqueta.setMaximumSize(new Dimension(100,50));
            PanelEtiqueta.setMaximumSize(new Dimension(100,50));
            if(Elemento == Lista.elementoActual) PanelEtiqueta.setBackground(Color.ORANGE);
            else PanelEtiqueta.setBackground(Color.CYAN);
            
            JLabel Etiqueta = new JLabel();
            Etiqueta.setText((String) Elemento.ObtenerValorPerro());
            Etiqueta.setBounds(0,0,20,15);
            Font fuente = new Font("Calibri", 3, 20);
            Etiqueta.setFont(fuente);
            
            JPanel PanelFlecha = new JPanel();
            PanelFlecha.setSize(new Dimension(100,50));
            PanelFlecha.setMaximumSize(new Dimension(100,50));
            PanelFlecha.setMaximumSize(new Dimension(100,50));
            
            JLabel Flecha = new JLabel();
            Flecha.setBounds(50, 25, 50, 50);
            Icon icono = new ImageIcon("src/Recursos/flecha.png");
            Flecha.setIcon(icono);
            
            PanelFlecha.add(Flecha);
            PanelEtiqueta.add(Etiqueta);
            
            PanelContenedor.add(PanelEtiqueta);
            PanelContenedor.add(PanelFlecha);
            
            if(ContadorNulos == Lista.TamañoLista){
                JPanel PanelNullo = new JPanel();
                PanelNullo.setSize(new Dimension(100,50));
                PanelNullo.setMaximumSize(new Dimension(100,50));
                PanelNullo.setMaximumSize(new Dimension(100,50));
                PanelNullo.setBackground(Color.RED);
               
            
                JLabel EtiquetaNullo = new JLabel();
                EtiquetaNullo.setText("Null");
                EtiquetaNullo.setBounds(0,0,20,15);
                Font fuente2 = new Font("Calibri", 3, 20);
                EtiquetaNullo.setFont(fuente2);
                
                PanelNullo.add(EtiquetaNullo);
                PanelContenedor.add(PanelNullo);
            }
            ContadorNulos++;
        }//Fin For
        Revalidar();
       }
      }
    }//Fin Graficar
    
    public void Estadisticas(){
      if(Lista.ListaVacia()){
        this.lbPrimerelemento.setText("Null");
        this.lbElementoActual.setText("Null");
        this.lbUlimoElemento.setText("Null");
        this.lbTamaño.setText(""+Lista.TamañoLista);
      }else{
        this.lbPrimerelemento.setText(""+Lista.inicioLista.ObtenerValorPerro());
        this.lbElementoActual.setText(Lista.elementoActual.ObtenerValorPerro().toString());
        this.lbUlimoElemento.setText((String) Lista.finLista.ObtenerValorPerro());
        this.lbTamaño.setText(""+Lista.TamañoLista);
      }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminarIndice;
    private javax.swing.JButton btnEliminarPrimero;
    private javax.swing.JButton btnEliminarUltimo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbElementoActual;
    private javax.swing.JLabel lbPrimerelemento;
    private javax.swing.JLabel lbTamaño;
    private javax.swing.JLabel lbUlimoElemento;
    private javax.swing.JTextField txtAgregar;
    private javax.swing.JTextField txtEliminarIndice;
    // End of variables declaration//GEN-END:variables
}
